---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate

  - name: install
    image: node:12
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true    
    commands:
      - npm ci

  - name: test
    image: node:12
    commands:
      - npm test

  - name: check-coverage
    image: node:12
    commands:
      - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/nodejsscan
    commands:
      - python /usr/src/app/cli.py -d dist

---
kind: secret
name: npm_token
data: 7uFoHnowZyWM6w7MyOYuJsf228yTMxHOeJYOVQ==
---
kind: signature
hmac: 6e0884bd8ca3b6dee53753eb2e231a28eb4e0052623f165c3243d477d68793f5

...
